# To start app:
#   gcloud app deploy app.yaml --project legal-leaf --version v1
# To delete app:
#   Get id by running:
#     gcloud app instances list
#   Then stop app with that id:
#     gcloud app instances delete id --service=default --version=v1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /webapi/summarize
  script: main.app

libraries:
- name: numpy
  version: "1.6.1"

- name: ssl
  version: latest

env_variables:
  NLTK_DATA: "lib/nltk_data/"

automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50